### PR TITLE
WIP: Spark version (new)

### PR DESCRIPTION
**Pull request by pomadchin**
Based on a #10 PR

### CODE REVIEW

**Comment by lossyrob** [comment]
Issue notes in review
- Masking issues
- Slowness in calculating breaks
- Zonal summary does not match previous version
- Performance

**Comment by pomadchin** [comment]
TODO: add settings to run server not only locally (currently it contains strong hardcoded restrictions)

**Comment by pomadchin** [comment]
https://github.com/geotrellis/geotrellis/issues/1305

**Comment by lossyrob** [comment]
@pomadchin Is this ready to be merged? I made a 0.9 branch, we are ready for this to be chatta demo master unless there is a reason not to.

**Comment by pomadchin** [comment]
@lossyrob it is ready, but has lots of time stats: https://github.com/pomadchin/geotrellis-chatta-demo/blob/spark-version/geotrellis/src/main/scala/geotrellis/chatta/ChattaServiceActor.scala#L95-L98

if that's ok, than that can be merged; or I can clear the code.

**Comment by lossyrob** [comment]
I think that is fine. Merging.

**Pull request merged**
